### ISSUE TITLE
[Integrations] Logs to GA

### ISSUE THREAD

**Issue by dkanter14** [Stedi/public-roadmap#38]
## Summary

With the ability to launch Functions on Stedi directly, users also need to be able to collect logs from those Functions. Logs help developers troubleshoot their integrations. In coordination with the launch of Functions, Logs will also be available to developers who need access to their logs.

## User experience

- [ ] Ability to collect logs from Functions

**Comment by pcholakov** [comment]
Going to inline this into #36 for now.
